
<a href='https://www.darshan.ac.in/'> <img src='https://www.darshan.ac.in/Content/media/DU_Logo.svg' width="250" height="300"/></a>
<pre>
<center><b><h1>Python Programming - 2101CS405</b></center>
<center><b><h1>Lab - 3</b></center>    
<pre>

# for and while loop

### 01) WAP to print 1 to 10

In [ ]:
for i in range(1,11):
    print(i)

1
2
3
4
5
6
7
8
9
10

### 02) WAP to print 1 to n

In [ ]:
no = int(input("Enter no : "));
for i in range(1,no):
    print(i)

Enter no : 11
1
2
3
4
5
6
7
8
9
10

### 03) WAP to print odd numbers between 1 to n

In [ ]:
no = int(input("Enter no : "))
for i in range(1,no):
   if i%2!=0:
    print(i)

Enter no : 5
1
3

### 04) WAP to print numbers between two given numbers which is divisible by 2 but not divisible by 3

In [ ]:
no1 = int(input("Enter no1 : "))
no2 = int(input("Enter no2 : "))
for i in range(no1,no2):
    if (i%2==0 and i%3!=0):
        print(i)

Enter no1 : 2
Enter no2 : 10
2
4
8

### 05) WAP to print sum of 1 to n numbers

In [ ]:
no = int(input("Enter no : "))
sum = 0
for i in range(1,no):
    sum = sum + i
    print(sum)

Enter no : 5
1
3
6
10

### 06) WAP to print sum of series 1 + 4 + 9 + 16 + 25 + 36 + ...n

In [ ]:
no = int(input("Enter no : "))
sum = 0 
for i in range(1,no+1):
    a = i * i
    sum = sum + a
print(sum)

Enter no : 9
285

### 07) WAP to print sum of series 1 – 2 + 3 – 4 + 5 – 6 + 7 ... n

In [ ]:
no = int(input("Enter no : "))
sum = 0
for i in range(1,no+1):
    if i%2==0:
        sum = sum-i
    else:
        sum = sum+i
print(sum)

Enter no : 3
2

### 08) WAP to print multiplication table of given number.

In [ ]:
no = int(input("Enter no : "))
for i in range(1,11):
    print(no," X ",i," = ",no*i)

Enter no : 5
5  X  1  =  5
5  X  2  =  10
5  X  3  =  15
5  X  4  =  20
5  X  5  =  25
5  X  6  =  30
5  X  7  =  35
5  X  8  =  40
5  X  9  =  45
5  X  10  =  50

### 09)WAP to find factorial of the given number

In [ ]:
no = int(input("Enter no : "))
factorial = 1
for i in range(1,no):
    factorial = no * i 
print(factorial)

Enter no : 4
12

### 10) WAP to find factors of the given number

In [ ]:
no = int(input("Enter no : "))
for i in range(1,no):
    if no%i==0:
        print(i)

Enter no : 8
1
2
4

### 11) WAP to find whether the given number is prime or not.

In [ ]:
no = int(input("Enter no : "))
for  i in range(1,no):
    if no%

### 12) WAP to print sum of digits of given number

In [ ]:
no = int(input("Enter no : "))
sum  = 0 
for i in range(1,no):
    if no%10==0:
        sum =

Enter no : 445

### 13) WAP to check whether the given number is palindrome or not

In [1]:
n = int(input("Enter Number : "))
sum = 0
temp = n
while(n > 0):
#     rem = n%10
    sum = sum * 10 + n % 10
    n = int(n / 10)
if temp == sum:
    print("Palindrome")
else:
    print("Not Palindrome")

Enter Number : 45
Not Palindrome

### 01) WAP to check whether the given number is Armstrong or not.

In [2]:
n = int(input("Enter Number : "))
sum = 0
count = 0
while(n > 0):
    rem = n % 10
    n = int(n / 10)
    count += 1
while(n > 0):
#     rem = n % 10
    sum += (n % 10)**count
    n = int(n / 10)
temp2 = n**count
if temp2 == sum:
    print("Armstrong")
else:
    print("Not Armstrong")

Enter Number : 45
Armstrong

### 02) WAP to find out prime numbers between given two numbers.

In [5]:
n1 = int(input("Enter Starting number"))
n2 = int(input("Enter Ending number"))
while(n1 <= n2):
    num = 2
    while(n1//2+ 1> num):
        if n1 % num == 0:
            num = -1
            break
        num += 1
    if num != -1:
        print(n1)
    n1 += 1

Enter Starting number10
Enter Ending number45
11
13
17
19
23
29
31
37
41
43

### 03) WAP to calculate x^y without using any function.

In [7]:
number = int(input("Enter Number : "))
power = int(input("Enter power : "))
sum = 0
if power == 0:
    print(1)
else:
    num = number
    while(power > 1):
        number*=num
        power-=1
    print(number)

Enter Number : 10
Enter power : 2
100

### 04) WAP to check whether the given number is perfect or not.
[Sum of factors including 1 excluding number itself]

In [8]:
n = int(input("Enter Number : "))
no = 1;
sum = 0
temp = n
while(no < n):
    if n % no == 0:
        sum += no
    no += 1
if temp == sum:
    print("Perfect")
else:
    print("Not Perfect")

Enter Number : 6
Perfect

### 05) WAP to find the sum of 1 + (1+2) + (1+2+3) + (1+2+3+4)+...+(1+2+3+4+....+n)

In [9]:
num = int(input("Enter Number : "))
sum = 0;
for i in range(1,num+1):
    for j in range(1,i+1):
        sum = sum + j
print(sum)

Enter Number : 5
35

### 06) WAP to print Multiplication Table up to n

In [10]:
n1 = int(input("Enter Number For Table : "))
n2 = int(input("Enter Last Number  "))
for i in range(1,n2+1):
    print(n1," * ",i," = ",n1*i)

Enter Number For Table : 4
Enter Last Number  8
4  *  1  =  4
4  *  2  =  8
4  *  3  =  12
4  *  4  =  16
4  *  5  =  20
4  *  6  =  24
4  *  7  =  28
4  *  8  =  32